### ISSUE TITLE
HU02 - Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by jflorez91** [jchernandezUA/vinylOS-ua#15]
|Identificador|HU02|
|-|-|
|**Nombre**|Consultar la información detallada de un álbum|
|**Descripción**|Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él|
|**Criterios de aceptación**|El usuario debe poder acceder a la pantalla donde se debe mostrar la información detallada del álbum.|
|Visualización del detalle del álbum| Se debe mostrar la siguiente información del álbum:<ul><li>Imagen del álbum.</li><li>Nombre del álbum.</li><li>Fecha de lanzamiento</li><li>Descripción del álbum.</li><li>Genero musical</li><li>Sello discrografico</li></ul>|
|Listados de pistas|Cada álbum debe mostrar un listado de sus pistas con: <ul><li>Nombre de la pista.</li><li>Duración de la pista</li><li> Se debe mostrar todas las pistas que pertenece al álbum</li></ul>|
|Listado de Intérpretes|Cada álbum debe listar los intérpretes con:<ul><li>Nombre de intérprete</li><li>Imagen del intérprete</li><li> Cuando se seleccióna el interprete, el usuario debe poder ver el detalle del interprete.</li></ul>|
|Comentarios del álbum| El álbum debe mostrar los comentarios asociados, incluyendo:<ul><li>Descripción del comentario</li><li>Calificación</li></ul> |
|Mockups|![AlbumDetail2](https://github.com/user-attachments/assets/77b9813e-fb93-4b8e-9d08-6c4a0bf87978)|

**Comment by jchernandezUA** [comment]
| Criterio      | Comentario                                           | Realizado por            |
|---------------|-----------------------------------------------------|---------------------------|
| Completo      | La descripción cubre los requisitos básicos para mostrar el detalle de los álbumes. |Jose Carlos Hernandez|
| Consistente   | La HU es consistente en su enfoque y criterios de aceptación; todos los puntos están alineados con la necesidad del usuario. |Jose Carlos Hernandez|
| Negociable    | Se observa flexibilidad en los criterios de aceptación, especialmente en la presentación de los álbumes. |Jose Carlos Hernandez|
| Valiosa       | Esta HU proporciona valor al usuario al permitirle explorar el catálogo de álbumes, lo que puede mejorar la experiencia general. |Jose Carlos Hernandez|
| Estimable     | La HU parece ser estimable a nivel de esfuerzo y tiempo. |Jose Carlos Hernandez|
| Pequeña       | Esta HU puede ser considerada pequeña, ya que los criterios de aceptación son claros y específicos. |Jose Carlos Hernandez|
| Comprobable   | Todos los criterios de aceptación son medibles y se pueden verificar al final del desarrollo. | Jose Carlos Hernandez      |

**Comment by jchernandezUA** [comment]
Según los comentarios del tutor habría que quitar la url del prototipo y documentrlo en el wiki
