### ISSUE TITLE
HU07 - Agregar álbum

### ISSUE THREAD

**Issue by jchernandezUA** [jchernandezUA/vinylOS-ua#2]
|Identificador|HU007|
|-|-|
|**Nombre**| Agregar álbum|
|**Descripción**| Como coleccionista quiero agregar álbum al listado para ampliar la los álbumes de la plataforma disponbiles|
|**Criterios de acpetación**| * Se debe ingresar el nombre del álbum|
||* El campo álbum no debe estar vacío|
||* Se debe agregar una url de imagen del álbum|
||* El campo imagen no debe ser vacío|
||* El campo imagen debe ser una url válida|
||* Se debe agregar la fecha de publicación del álbum1
||* El campo fecha de publicación no debe ser vacío|
||* El campo fecha debe tener un formato de dd/mm/yyyy|
||* Se debe ingresar la descripción del álbum|
||* El campo de descripción no debe ser vacío|
||* Se debe ingresar un género del álbum|
||* El campo genero debe ser solo Classical, Salsa, Rock, o Folk|
||* Se debe ingresar un record del cual pertenece el álbum|
||* El record debe ser solo Sony Music, EMI, Discos Fuentes, Elektra o Fania Records|
|Mockups|  <img src="https://github.com/user-attachments/assets/d2713311-5dbb-457f-8e2a-b525970fdc7e" width=67% height=67%>|

**Comment by jflorez91** [comment]
| Criterio      | Comentario                                           | Realizado por            |
|---------------|-----------------------------------------------------|---------------------------|
| Completo      | La descripción cubre y enfoca la necesidad del negocio para la creación de un álbum |@jflorez91|
| Consistente   | La HU y los criterios de aceptación es consistente con las necesidades del usuario de acuerdo a la aplicación |@jflorez91|
| Negociable    | Se observa flexibilidad en los criterios de aceptación |@jflorez91|
| Valiosa       | Esta HU proporciona un gran valor al usuario permitiendo agregar álbumes y así poder ampliar la muestra en la aplicación, lo que puede mejorar la experiencia general. |@jflorez91|
| Estimable     | Dado la descripción general y los criterios de aceptación se hace estimable la HU|@jflorez91|
| Pequeña       | Esta HU puede ser considerada pequeña, ya que los criterios de aceptación son claros y específicos. |@jflorez91|
| Comprobable   | Todos los criterios de aceptación a ser medible se puede comprobar facilmente. | @jflorez91|
