### ISSUE TITLE
HU08 - Asociar tracks con un álbum

### ISSUE THREAD

**Issue by jchernandezUA** [jchernandezUA/vinylOS-ua#4]
|Identificador|HU08|
|-|-|
|**Nombre**|Asociar tracks con un álbum|
|**Descripción**|Como coleccionista quiero agregar tracks a un álbum para actualizar el catálogo|
|**Criterios de aceptación**| * Se debe mostrar una opción para "Agregar track" en la pantalla del detall de álbum |
||* Se debe listar el total de canciones disponibles que no estén ya asociadas |
||* Se debe poder seleccionar multiples canciones|
|| * Se debe confirmar que se han guardado las canciones|
|| * Se debe volver a cargar la lista de canciones del álbum|
|Mockups|  <img src="https://github.com/user-attachments/assets/73e84023-5a0b-494c-8236-d20b40787beb" width=67% height=67%>|

**Comment by jflorez91** [comment]
| Criterio      | Comentario                                           | Realizado por            |
|---------------|-----------------------------------------------------|---------------------------|
| Completo      | La descripción cubre y enfoca la necesidad del negocio para la agregación de una canción a un álbum |@jflorez91|
| Consistente   | La HU y los criterios de aceptación es consistente con las necesidades del usuario de acuerdo a la aplicación |@jflorez91|
| Negociable    | Se observa flexibilidad en los criterios de aceptación. |@jflorez91|
| Valiosa       | Esta HU proporciona un gran valor al usuario permitiendo agregar canciones a un álbum y así poder ampliar la muestra en la aplicación, lo que puede mejorar la experiencia general. |@jflorez91|
| Estimable     | Dado la descripción general y los criterios de aceptación se hace estimable la HU|@jflorez91|
| Pequeña       | Esta HU puede ser considerada pequeña, ya que los criterios de aceptación son claros y específicos. |@jflorez91|
| Comprobable   | Todos los criterios de aceptación a ser medible se puede comprobar facilmente. | @jflorez91|
